apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codex-frontend
  template:
    metadata:
      labels:
        app: codex-frontend
    spec:
      containers:
        - name: frontend
          image: myregistry/codex-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: codex-frontend
spec:
  selector:
    app: codex-frontend
  ports:
    - port: 80
      targetPort: 80
