version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: codex
      POSTGRES_USER: codex
      POSTGRES_PASSWORD: codex
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/codex
      SPRING_DATASOURCE_USERNAME: codex
      SPRING_DATASOURCE_PASSWORD: codex
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
