version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: codex
      POSTGRES_USER: codex
      POSTGRES_PASSWORD: codex
    ports:
      - "${DB_PORT:-5432}:5432"
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      SERVER_PORT: ${BACKEND_PORT:-8080}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:30080}
      SPRING_DATASOURCE_USERNAME: codex
      SPRING_DATASOURCE_PASSWORD: codex
    ports:
      - "${BACKEND_PORT:-8080}:8080"
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-4200}:80"
