apiVersion: v1
kind: Secret
metadata:
  name: codex-db-credentials
  labels:
    app: codex-db
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codex-db-init
  labels:
    app: codex-db
data:
  init-keycloak-db.sql: |
    {{- if ne .Values.keycloak.db.user .Values.db.user }}
    CREATE USER {{ .Values.keycloak.db.user }} WITH ENCRYPTED PASSWORD '{{ .Values.keycloak.db.password }}';
    {{- end }}
    CREATE DATABASE {{ .Values.keycloak.db.name }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.keycloak.db.name }} TO {{ .Values.keycloak.db.user }};
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codex-db-pvc
  labels:
    app: codex-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-db
  labels:
    app: codex-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codex-db
  template:
    metadata:
      labels:
        app: codex-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: codex-db-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: codex-db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: codex-db-credentials
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: codex-db-pvc
        - name: init-script
          configMap:
            name: codex-db-init
---
apiVersion: v1
kind: Service
metadata:
  name: codex-db
  labels:
    app: codex-db
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: codex-db
  ports:
    - port: 5432
      targetPort: 5432
{{- if .Values.db.service.nodePort }}
      nodePort: {{ .Values.db.service.nodePort }}
{{- end }}
