apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: my-keycloak
spec:
  instances: {{ .Values.keycloak.instances }}
  db:
    vendor: postgres
    host: codex-db.{{ .Release.Namespace }}.svc.cluster.local
    port: 5432
    database: {{ .Values.keycloak.db.name }}
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  additionalOptions:
    - name: hostname-strict
      value: "false"
    - name: http-enabled
      value: "true"
  ingress:
    enabled: true
