apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    app: keycloak
type: Opaque
stringData:
  username: {{ .Values.keycloak.db.user }}
  password: {{ .Values.keycloak.db.password }}
