apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: codex-backend
build:
  artifacts:
    - image: codex-backend
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: true
deploy:
  helm:
    releases:
      - name: codex
        chartPath: ../helm/codex
        namespace: dev
        createNamespace: true
        valuesFiles:
          - ../helm/codex/values-dev.yaml
        setValueTemplates:
          image.backend: "{{.IMAGE_FULLY_QUALIFIED}}"
