apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: codex-backend
build:
  artifacts:
    - image: codex-backend
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - ../kubernetes/dev/namespace.yaml
      - ../kubernetes/dev/db.yaml
      - ../kubernetes/dev/db-secret.yaml
      - ../kubernetes/dev/backend-skaffold.yaml
