apiVersion: v2
name: codex
description: Umbrella chart to deploy all Codex components together
type: application
version: 0.1.0
dependencies:
  - name: codex-backend
    alias: backend
    version: 0.1.0
    repository: file://../backend
  - name: codex-frontend
    alias: frontend
    version: 0.1.0
    repository: file://../frontend
  - name: codex-database
    alias: database
    version: 0.1.0
    repository: file://../database
  - name: codex-keycloak
    alias: keycloak
    version: 0.1.0
    repository: file://../keycloak
