git:
  branch: "dev"

backend:
  service:
    nodePort: 30081
  env:
    FRONTEND_URL: "http://localhost:30080"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://my-keycloak-service.dev:8080/realms/codex/protocol/openid-connect/certs"
frontend:
  service:
    nodePort: 30080
  env:
    API_URL: "http://localhost:30081"
    KEYCLOAK_URL: "http://localhost:30001"
db:
  service:
    nodePort: 30082
keycloak:
  service:
    nodePort: 30001
