image:
  backend: ""
  frontend: ""

git:
  branch: "dev"

backend:
  service:
    type: NodePort
    nodePort: 30081
  env:
    DB_HOST: codex-db
    DB_PORT: "5432"
    FRONTEND_URL: "http://localhost:30080"
    SPRING_DATASOURCE_USERNAME: codex
    SPRING_DATASOURCE_PASSWORD: codex
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://my-keycloak-service.dev:8080/realms/codex"

frontend:
  service:
    type: NodePort
    nodePort: 30080
  env:
    API_URL: "http://localhost:30081"
    KEYCLOAK_URL: "http://localhost:30001"
    KEYCLOAK_REALM: codex
    KEYCLOAK_CLIENT_ID: codex-frontend

db:
  name: codex
  user: codex
  password: codex
  storage: 1Gi
  service:
    type: NodePort
    nodePort: 30082

keycloak:
  image: quay.io/keycloak/keycloak:26.3.3
  instances: 1
  admin:
    user: admin
    password: admin
  db:
    name: keycloak
    user: codex
    password: codex
  realm:
    id: codex12
    name: codex
    displayName: codex
    clientId: codex-frontend
  service:
    type: NodePort
    nodePort: 30001
