backend:
  service:
    nodePort: 32081
  env:
    FRONTEND_URL: "http://localhost:32080"
frontend:
  service:
    nodePort: 32080
  env:
    API_URL: "http://localhost:32081"
    KEYCLOAK_URL: "http://localhost:32001"
db:
  service:
    nodePort: 32082
keycloak:
  proxy:
    service:
      nodePort: 32001
