apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-backend
  labels:
    app: codex-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codex-backend
  template:
    metadata:
      labels:
        app: codex-backend
    spec:
      containers:
        - name: backend
          # dynamically use the image Jenkins pushed
          image: ${IMAGE_BACKEND}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "codex-db"          # points to the Service name
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
      # if your registry needs auth, uncomment this:
      # imagePullSecrets:
      #   - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: codex-backend
  labels:
    app: codex-backend
spec:
  type: NodePort
  selector:
    app: codex-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081
