apiVersion: v1
metadata:
  namespace: dev
  name: codex-db-credentials
  labels:
    app: codex-db
type: Opaque
kind: Secret
stringData:
  POSTGRES_DB: codex
  POSTGRES_USER: codex
  POSTGRES_PASSWORD: codex