apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-frontend
  labels:
    app: codex-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codex-frontend
  template:
    metadata:
      labels:
        app: codex-frontend
    spec:
      containers:
        - name: frontend
          # pull the exact image Jenkins just pushed
          image: ${IMAGE_FRONTEND}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      # uncomment/create this if your registry requires auth
      # imagePullSecrets:
      #   - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: codex-frontend
  labels:
    app: codex-frontend
spec:
  type: NodePort
  selector:
    app: codex-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
