spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/codex
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jooq:
    sql-dialect: POSTGRES

frontendUrl: ${FRONTEND_URL}

logging.level.org.jooq.tools.LoggerListener: DEBUG

