spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/codex
    username: codex
    password: codex
  jooq:
    sql-dialect: POSTGRES

logging.level.org.jooq.tools.LoggerListener: DEBUG

server:
  port: ${SERVER_PORT:8080}

