spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/codex
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jooq:
    sql-dialect: POSTGRES
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://my-keycloak-service.dev:8080/realms/codex/protocol/openid-connect/certs"

frontendUrl: ${FRONTEND_URL}

logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG
    com.example.codex.config.JwtAuthConverter: DEBUG

